# SPDX-FileCopyrightText: 2025 Alex Willmer <alex@moreati.org.uk>
# SPDX-License-Identifier: MIT

name: Build packages

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: pip install build
      - run: python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          if-no-files-found: error

  wheels:
    name: wheels-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        # https://github.com/actions/runner-images/tree/main/images
        os:
          - macos-15-intel
          - macos-latest
          - ubuntu-24.04-arm
          - ubuntu-latest
        include:
          - os: windows-latest
            LZMA_CF_INCLUDE_DIRS: 'xz\src\liblzma\api'
            LZMA_CF_LIBRARY_DIRS: 'xz\windows\build'
    steps:
      - uses: msys2/setup-msys2@v2
        env:
          arch_lookup_json: '{"X64": "ucrt-x86_64", "ARM64": "clang-aarch64"}'
        with:
          msystem: UCRT64
          install: >
            mingw-w64-${{ fromJSON(env.arch_lookup_json)[runner.arch] }}-cmake
            mingw-w64-${{ fromJSON(env.arch_lookup_json)[runner.arch] }}-gcc
            mingw-w64-${{ fromJSON(env.arch_lookup_json)[runner.arch] }}-gettext-tools
            git libtool make po4a
        if: ${{ runner.os == 'Windows' }}
      - uses: actions/checkout@v5
      - uses: pypa/cibuildwheel@v3.2.0
        env:
          LZMA_CF_INCLUDE_DIRS: ${{ matrix.LZMA_CF_INCLUDE_DIRS || null }}
          LZMA_CF_LIBRARY_DIRS: ${{ matrix.LZMA_CF_LIBRARY_DIRS || null }}
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
          if-no-files-found: error

  merge:
    needs:
      - sdist
      - wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: dist
          delete-merged: true
